<template lang="pug">
  form(@submit.prevent="onSubmit" :action="action" :name="formName" netlify)
    input(type="hidden" v-model="honeypot")
    input(type="hidden" name="to" v-model="form.to")
    input(type="hidden" name="subject" v-model="form.subject")
    .fields
      .field.half
        input(type='text', name='name', placeholder='Name' v-model="form.name" required)
      .field.half
        input(type='email', name='email', placeholder='Email' v-model="form.email" required)
      .field
        textarea(name='text', placeholder='Message', rows='6' v-model="form.text" required)
    ul.actions.special
      li
        input(type='submit', value='Send Message')
</template>

<script>
import axios from "axios";
import querystring from "qs";
export default {
  data() {
    return {
      form: {
        name: "",
        email: "",
        subject: "New Message Generated by Your Site!",
        text: ""
      },
      action: "contact",
      formName: "contact",
      honeypot: "",
      isLoading: false,
      status: ""
    };
  },
  computed: {
    submissionPayload() {
      return {
        "form-name": this.formName,
        to: "martin.frackerjr@gmail.com",
        name: this.form.name,
        email: this.form.email,
        subject: this.form.subject,
        text: this.form.text
      };
    }
  },
  methods: {
    onSubmit() {
      if (this.honeypot !== "") {
        return;
      }
      let formData = querystring.stringify(this.submissionPayload);
      this.isLoading = true;
      axios
        .post(this.action, formData)
        .then(() => {
          this.isLoading = false;
          this.status = true;
        })
        .catch(() => {
          this.status = false;
          setTimeout(() => {
            this.status = "";
          }, 2000);
        });
    }
  }
};
</script>

<style lang="less" scoped>
#contact-form {
  margin-top: 30px;
}
#message {
  height: 12em;
}
</style>
